#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

FW_DIR="$DESTDIR/lib/firmware"

# install Aetheros AR7010 firmware
mkdir -p $FW_DIR
  cp ar7010/* $FW_DIR

# install Aetheros AR9170 firmware
mkdir -p $FW_DIR
  cp ar9170/* $FW_DIR

# install Aetheros AR9271 firmware
mkdir -p $FW_DIR
  cp ar9271/* $FW_DIR

# install broadcom B43 firmware
mkdir -p $FW_DIR/b43
  cp b43/* $FW_DIR/b43

# install Intel ipw2100 firmware
mkdir -p $FW_DIR
  cp ipw2100/* $FW_DIR

# install Intel ipw2200 firmware
mkdir -p $FW_DIR
  cp ipw2200/* $FW_DIR

# install Intel iwlwifi-100 firmware
mkdir -p $FW_DIR
  cp iwlwifi-100/* $FW_DIR

# install Intel iwlwifi-1000 firmware
mkdir -p $FW_DIR
  cp iwlwifi-1000/* $FW_DIR

# install Intel iwlwifi-3945 firmware
mkdir -p $FW_DIR
  cp iwlwifi-3945/* $FW_DIR

# install Intel iwlwifi-4965 firmware
mkdir -p $FW_DIR
  cp iwlwifi-4965/* $FW_DIR

# install Intel iwlwifi-5000 firmware
mkdir -p $FW_DIR
  cp iwlwifi-5000/* $FW_DIR

# install Intel iwlwifi-5150 firmware
mkdir -p $FW_DIR
  cp iwlwifi-5150/* $FW_DIR

# install Intel iwlwifi-6000 firmware
mkdir -p $FW_DIR
  cp iwlwifi-6000/* $FW_DIR

# install Intel iwlwifi-6050 firmware
mkdir -p $FW_DIR
  cp iwlwifi-6050/* $FW_DIR

# install VIA vt6656 firmware
mkdir -p $FW_DIR
  cp via-vt6656/* $FW_DIR

# install ORINOCO Agere firmware
mkdir -p $FW_DIR
  cp orinoco/* $FW_DIR

# install Ralink 2561 firmware
mkdir -p $FW_DIR
  cp rt2561/* $FW_DIR

# install Ralink 2661 firmware
mkdir -p $FW_DIR
  cp rt2661/* $FW_DIR

# install Ralink 2860 firmware
mkdir -p $FW_DIR
  cp rt2860/* $FW_DIR

# install Ralink 2870 firmware
mkdir -p $FW_DIR
  cp rt2870/* $FW_DIR

# install Ralink 3070 firmware
mkdir -p $FW_DIR
  cp rt3070/* $FW_DIR

# install Ralink 3071 firmware
mkdir -p $FW_DIR
  cp rt3071/* $FW_DIR

# install Ralink 3090 firmware
mkdir -p $FW_DIR
  cp rt3090/* $FW_DIR

# install Ralink 73 firmware
mkdir -p $FW_DIR
  cp rt73/* $FW_DIR

# install ZyDAS ZD1211(b) firmware
mkdir -p $FW_DIR/zd1211
  cp zd1211/* $FW_DIR/zd1211

